### PR TITLE
Support Google AMP

### LINKED ISSUE #20: Integrate Google AMP
Need to do some evaluation on this topic and see if we can integrate [Accelerated Mobile Pages](https://www.ampproject.org/).

https://www.ampproject.org/docs/get_started/create_page.html
https://www.ampproject.org/docs/guides/validate.html

### PR DESCRIPTION
**Pull request by poppastring**
closes #20

### CODE REVIEW

**Comment by shanselman** [comment]
Cool. I'm back. So is this basically done? Did you finish everything we talked about?

**Comment by poppastring** [comment]
Yes this is done 99%
YouTube, Images, and Twitter are done, but Twitter converts are not precise, as in they end up being just quoted text (I need time to fix that)
 I actually have one more update for you after this one, I need to send you  a pull request for that also.

**Comment by poppastring** [comment]
Just realized that I did not create a feature branch, you actually have all my latest changes. Do some local tests and let me know what you find. Let me know if there are any issues.

**Comment by shanselman** [comment]
No worries. I'll check it out next week, I'm on vacation. May have time to Skype.

**Pull request merged**
